// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RssManager.Database;

#nullable disable

namespace RssManager.Migrations
{
    [DbContext(typeof(Database.XmlContext))]
    [Migration("20230128172223_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("RssManager.Models.XmlItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("XmlText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("XmlItems");
                });
#pragma warning restore 612, 618
        }
    }
}
